[2024-10-25 21:30:00] error: Uncaught Exception: listen EADDRINUSE: address already in use :::3004
{
  "code": "EADDRINUSE",
  "errno": -4091,
  "syscall": "listen",
  "address": "::",
  "port": 3004,
  "stack": "Error: listen EADDRINUSE: address already in use :::3004\n    at Server.setupListenHandle [as _listen2] (node:net:1904:16)\n    at listenInCluster (node:net:1961:12)\n    at Server.listen (node:net:2063:7)\n    at new WebSocketServer (C:\\Users\\dange\\fieldhive 3.0\\node_modules\\.pnpm\\ws@8.18.0\\node_modules\\ws\\lib\\websocket-server.js:102:20)\n    at createWebSocketServer (C:\\Users\\dange\\fieldhive 3.0\\packages\\api\\src\\index.ts:37:17)\n    at startServer (C:\\Users\\dange\\fieldhive 3.0\\packages\\api\\src\\index.ts:100:21)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"
}
[2024-10-25 21:31:20] error: Uncaught Exception: listen EADDRINUSE: address already in use :::3004
{
  "code": "EADDRINUSE",
  "errno": -4091,
  "syscall": "listen",
  "address": "::",
  "port": 3004,
  "stack": "Error: listen EADDRINUSE: address already in use :::3004\n    at Server.setupListenHandle [as _listen2] (node:net:1904:16)\n    at listenInCluster (node:net:1961:12)\n    at Server.listen (node:net:2063:7)\n    at new WebSocketServer (C:\\Users\\dange\\fieldhive 3.0\\node_modules\\.pnpm\\ws@8.18.0\\node_modules\\ws\\lib\\websocket-server.js:102:20)\n    at createWebSocketServer (C:\\Users\\dange\\fieldhive 3.0\\packages\\api\\src\\index.ts:37:17)\n    at startServer (C:\\Users\\dange\\fieldhive 3.0\\packages\\api\\src\\index.ts:100:21)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"
}
[2024-10-25 21:31:56] error: Error creating account: null value in column "property_id" of relation "billing_address" violates not-null constraint
{
  "query": "\n                INSERT INTO billing_address (\n                    account_id,\n                    address_1,\n                    city,\n                    province,\n                    postal_code,\n                    country\n                ) VALUES ($1, $2, $3, $4, $5, $6)\n            ",
  "parameters": [
    "1689d2da-cc6c-45a0-b473-285ff5260094",
    "123 Main St",
    "Test City",
    "Test State",
    "12345",
    "Test Country"
  ],
  "driverError": {
    "length": 363,
    "name": "error",
    "severity": "ERROR",
    "code": "23502",
    "detail": "Failing row contains (7433682f-7bd1-4107-8f96-df727afcb5ec, 1689d2da-cc6c-45a0-b473-285ff5260094, null, 123 Main St, null, 12345, Test City, Test State, Test Country).",
    "schema": "public",
    "table": "billing_address",
    "column": "property_id",
    "file": "execMain.c",
    "line": "2009",
    "routine": "ExecConstraints"
  },
  "length": 363,
  "severity": "ERROR",
  "code": "23502",
  "detail": "Failing row contains (7433682f-7bd1-4107-8f96-df727afcb5ec, 1689d2da-cc6c-45a0-b473-285ff5260094, null, 123 Main St, null, 12345, Test City, Test State, Test Country).",
  "schema": "public",
  "table": "billing_address",
  "column": "property_id",
  "file": "execMain.c",
  "line": "2009",
  "routine": "ExecConstraints",
  "stack": "QueryFailedError: null value in column \"property_id\" of relation \"billing_address\" violates not-null constraint\n    at PostgresQueryRunner.query (C:\\Users\\dange\\fieldhive 3.0\\node_modules\\.pnpm\\typeorm@0.3.20_pg@8.13.1_ts-node@10.9.2_@types+node@20.17.1_typescript@5.6.3_\\src\\driver\\postgres\\PostgresQueryRunner.ts:331:19)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at DataSource.query (C:\\Users\\dange\\fieldhive 3.0\\node_modules\\.pnpm\\typeorm@0.3.20_pg@8.13.1_ts-node@10.9.2_@types+node@20.17.1_typescript@5.6.3_\\src\\data-source\\DataSource.ts:538:20)\n    at C:\\Users\\dange\\fieldhive 3.0\\packages\\api\\src\\routes\\account.routes.ts:145:13"
}
[2024-10-25 21:32:13] error: Uncaught Exception: listen EADDRINUSE: address already in use :::3004
{
  "code": "EADDRINUSE",
  "errno": -4091,
  "syscall": "listen",
  "address": "::",
  "port": 3004,
  "stack": "Error: listen EADDRINUSE: address already in use :::3004\n    at Server.setupListenHandle [as _listen2] (node:net:1904:16)\n    at listenInCluster (node:net:1961:12)\n    at Server.listen (node:net:2063:7)\n    at new WebSocketServer (C:\\Users\\dange\\fieldhive 3.0\\node_modules\\.pnpm\\ws@8.18.0\\node_modules\\ws\\lib\\websocket-server.js:102:20)\n    at createWebSocketServer (C:\\Users\\dange\\fieldhive 3.0\\packages\\api\\src\\index.ts:37:17)\n    at startServer (C:\\Users\\dange\\fieldhive 3.0\\packages\\api\\src\\index.ts:100:21)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"
}
[2024-10-25 21:32:49] error: Uncaught Exception: listen EADDRINUSE: address already in use :::3004
{
  "code": "EADDRINUSE",
  "errno": -4091,
  "syscall": "listen",
  "address": "::",
  "port": 3004,
  "stack": "Error: listen EADDRINUSE: address already in use :::3004\n    at Server.setupListenHandle [as _listen2] (node:net:1904:16)\n    at listenInCluster (node:net:1961:12)\n    at Server.listen (node:net:2063:7)\n    at new WebSocketServer (C:\\Users\\dange\\fieldhive 3.0\\node_modules\\.pnpm\\ws@8.18.0\\node_modules\\ws\\lib\\websocket-server.js:102:20)\n    at createWebSocketServer (C:\\Users\\dange\\fieldhive 3.0\\packages\\api\\src\\index.ts:37:17)\n    at startServer (C:\\Users\\dange\\fieldhive 3.0\\packages\\api\\src\\index.ts:100:21)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"
}
[2024-10-25 21:33:03] error: Error creating account: null value in column "billing_address" of relation "properties" violates not-null constraint
{
  "query": "\n                INSERT INTO properties (created_at, updated_at)\n                VALUES (NOW(), NOW())\n                RETURNING property_id\n            ",
  "driverError": {
    "length": 328,
    "name": "error",
    "severity": "ERROR",
    "code": "23502",
    "detail": "Failing row contains (9dec97bf-f4f8-4013-9fa3-6cb3cbc02fe1, null, null, null, 2024-10-26 04:33:04.700081, 2024-10-26 04:33:04.700081).",
    "schema": "public",
    "table": "properties",
    "column": "billing_address",
    "file": "execMain.c",
    "line": "2009",
    "routine": "ExecConstraints"
  },
  "length": 328,
  "severity": "ERROR",
  "code": "23502",
  "detail": "Failing row contains (9dec97bf-f4f8-4013-9fa3-6cb3cbc02fe1, null, null, null, 2024-10-26 04:33:04.700081, 2024-10-26 04:33:04.700081).",
  "schema": "public",
  "table": "properties",
  "column": "billing_address",
  "file": "execMain.c",
  "line": "2009",
  "routine": "ExecConstraints",
  "stack": "QueryFailedError: null value in column \"billing_address\" of relation \"properties\" violates not-null constraint\n    at PostgresQueryRunner.query (C:\\Users\\dange\\fieldhive 3.0\\node_modules\\.pnpm\\typeorm@0.3.20_pg@8.13.1_ts-node@10.9.2_@types+node@20.17.1_typescript@5.6.3_\\src\\driver\\postgres\\PostgresQueryRunner.ts:331:19)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at DataSource.query (C:\\Users\\dange\\fieldhive 3.0\\node_modules\\.pnpm\\typeorm@0.3.20_pg@8.13.1_ts-node@10.9.2_@types+node@20.17.1_typescript@5.6.3_\\src\\data-source\\DataSource.ts:538:20)\n    at C:\\Users\\dange\\fieldhive 3.0\\packages\\api\\src\\routes\\account.routes.ts:147:32"
}
[2024-10-25 21:33:17] error: Uncaught Exception: listen EADDRINUSE: address already in use :::3004
{
  "code": "EADDRINUSE",
  "errno": -4091,
  "syscall": "listen",
  "address": "::",
  "port": 3004,
  "stack": "Error: listen EADDRINUSE: address already in use :::3004\n    at Server.setupListenHandle [as _listen2] (node:net:1904:16)\n    at listenInCluster (node:net:1961:12)\n    at Server.listen (node:net:2063:7)\n    at new WebSocketServer (C:\\Users\\dange\\fieldhive 3.0\\node_modules\\.pnpm\\ws@8.18.0\\node_modules\\ws\\lib\\websocket-server.js:102:20)\n    at createWebSocketServer (C:\\Users\\dange\\fieldhive 3.0\\packages\\api\\src\\index.ts:37:17)\n    at startServer (C:\\Users\\dange\\fieldhive 3.0\\packages\\api\\src\\index.ts:100:21)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"
}
[2024-10-25 21:33:51] error: Uncaught Exception: listen EADDRINUSE: address already in use :::3004
{
  "code": "EADDRINUSE",
  "errno": -4091,
  "syscall": "listen",
  "address": "::",
  "port": 3004,
  "stack": "Error: listen EADDRINUSE: address already in use :::3004\n    at Server.setupListenHandle [as _listen2] (node:net:1904:16)\n    at listenInCluster (node:net:1961:12)\n    at Server.listen (node:net:2063:7)\n    at new WebSocketServer (C:\\Users\\dange\\fieldhive 3.0\\node_modules\\.pnpm\\ws@8.18.0\\node_modules\\ws\\lib\\websocket-server.js:102:20)\n    at createWebSocketServer (C:\\Users\\dange\\fieldhive 3.0\\packages\\api\\src\\index.ts:37:17)\n    at startServer (C:\\Users\\dange\\fieldhive 3.0\\packages\\api\\src\\index.ts:100:21)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"
}
[2024-10-25 21:34:25] error: Error creating account: null value in column "property_id" of relation "billing_address" violates not-null constraint
{
  "query": "\n                INSERT INTO billing_address (\n                    account_id,\n                    address_1,\n                    city,\n                    province,\n                    postal_code,\n                    country\n                ) VALUES ($1, $2, $3, $4, $5, $6)\n            ",
  "parameters": [
    "59b76285-3113-4d88-aa75-8673d513ef5b",
    "123 Main St",
    "Test City",
    "Test State",
    "12345",
    "Test Country"
  ],
  "driverError": {
    "length": 363,
    "name": "error",
    "severity": "ERROR",
    "code": "23502",
    "detail": "Failing row contains (10d0a061-ac62-43ba-ba3c-9b1895e9eef8, 59b76285-3113-4d88-aa75-8673d513ef5b, null, 123 Main St, null, 12345, Test City, Test State, Test Country).",
    "schema": "public",
    "table": "billing_address",
    "column": "property_id",
    "file": "execMain.c",
    "line": "2009",
    "routine": "ExecConstraints"
  },
  "length": 363,
  "severity": "ERROR",
  "code": "23502",
  "detail": "Failing row contains (10d0a061-ac62-43ba-ba3c-9b1895e9eef8, 59b76285-3113-4d88-aa75-8673d513ef5b, null, 123 Main St, null, 12345, Test City, Test State, Test Country).",
  "schema": "public",
  "table": "billing_address",
  "column": "property_id",
  "file": "execMain.c",
  "line": "2009",
  "routine": "ExecConstraints",
  "stack": "QueryFailedError: null value in column \"property_id\" of relation \"billing_address\" violates not-null constraint\n    at PostgresQueryRunner.query (C:\\Users\\dange\\fieldhive 3.0\\node_modules\\.pnpm\\typeorm@0.3.20_pg@8.13.1_ts-node@10.9.2_@types+node@20.17.1_typescript@5.6.3_\\src\\driver\\postgres\\PostgresQueryRunner.ts:331:19)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at DataSource.query (C:\\Users\\dange\\fieldhive 3.0\\node_modules\\.pnpm\\typeorm@0.3.20_pg@8.13.1_ts-node@10.9.2_@types+node@20.17.1_typescript@5.6.3_\\src\\data-source\\DataSource.ts:538:20)\n    at C:\\Users\\dange\\fieldhive 3.0\\packages\\api\\src\\routes\\account.routes.ts:146:13"
}
[2024-10-25 21:36:27] error: Uncaught Exception: listen EADDRINUSE: address already in use :::3004
{
  "code": "EADDRINUSE",
  "errno": -4091,
  "syscall": "listen",
  "address": "::",
  "port": 3004,
  "stack": "Error: listen EADDRINUSE: address already in use :::3004\n    at Server.setupListenHandle [as _listen2] (node:net:1904:16)\n    at listenInCluster (node:net:1961:12)\n    at Server.listen (node:net:2063:7)\n    at new WebSocketServer (C:\\Users\\dange\\fieldhive 3.0\\node_modules\\.pnpm\\ws@8.18.0\\node_modules\\ws\\lib\\websocket-server.js:102:20)\n    at createWebSocketServer (C:\\Users\\dange\\fieldhive 3.0\\packages\\api\\src\\index.ts:37:17)\n    at startServer (C:\\Users\\dange\\fieldhive 3.0\\packages\\api\\src\\index.ts:100:21)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"
}
[2024-10-25 21:37:23] error: Error creating account: null value in column "billing_address" of relation "properties" violates not-null constraint
{
  "query": "\n                INSERT INTO properties (created_at, updated_at)\n                VALUES (NOW(), NOW())\n                RETURNING property_id\n            ",
  "driverError": {
    "length": 328,
    "name": "error",
    "severity": "ERROR",
    "code": "23502",
    "detail": "Failing row contains (5c6b3f07-86fd-4c5d-a9bf-ed97889eaea8, null, null, null, 2024-10-26 04:37:24.427912, 2024-10-26 04:37:24.427912).",
    "schema": "public",
    "table": "properties",
    "column": "billing_address",
    "file": "execMain.c",
    "line": "2009",
    "routine": "ExecConstraints"
  },
  "length": 328,
  "severity": "ERROR",
  "code": "23502",
  "detail": "Failing row contains (5c6b3f07-86fd-4c5d-a9bf-ed97889eaea8, null, null, null, 2024-10-26 04:37:24.427912, 2024-10-26 04:37:24.427912).",
  "schema": "public",
  "table": "properties",
  "column": "billing_address",
  "file": "execMain.c",
  "line": "2009",
  "routine": "ExecConstraints",
  "stack": "QueryFailedError: null value in column \"billing_address\" of relation \"properties\" violates not-null constraint\n    at PostgresQueryRunner.query (C:\\Users\\dange\\fieldhive 3.0\\node_modules\\.pnpm\\typeorm@0.3.20_pg@8.13.1_ts-node@10.9.2_@types+node@20.17.1_typescript@5.6.3_\\src\\driver\\postgres\\PostgresQueryRunner.ts:331:19)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at DataSource.query (C:\\Users\\dange\\fieldhive 3.0\\node_modules\\.pnpm\\typeorm@0.3.20_pg@8.13.1_ts-node@10.9.2_@types+node@20.17.1_typescript@5.6.3_\\src\\data-source\\DataSource.ts:538:20)\n    at C:\\Users\\dange\\fieldhive 3.0\\packages\\api\\src\\routes\\account.routes.ts:149:32"
}
[2024-10-25 21:38:19] error: Uncaught Exception: listen EADDRINUSE: address already in use :::3004
{
  "code": "EADDRINUSE",
  "errno": -4091,
  "syscall": "listen",
  "address": "::",
  "port": 3004,
  "stack": "Error: listen EADDRINUSE: address already in use :::3004\n    at Server.setupListenHandle [as _listen2] (node:net:1904:16)\n    at listenInCluster (node:net:1961:12)\n    at Server.listen (node:net:2063:7)\n    at new WebSocketServer (C:\\Users\\dange\\fieldhive 3.0\\node_modules\\.pnpm\\ws@8.18.0\\node_modules\\ws\\lib\\websocket-server.js:102:20)\n    at createWebSocketServer (C:\\Users\\dange\\fieldhive 3.0\\packages\\api\\src\\index.ts:37:17)\n    at startServer (C:\\Users\\dange\\fieldhive 3.0\\packages\\api\\src\\index.ts:100:21)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"
}
[2024-10-25 21:38:29] error: Error creating account: null value in column "property_id" of relation "billing_address" violates not-null constraint
{
  "query": "\n                INSERT INTO billing_address (\n                    account_id,\n                    address_1,\n                    city,\n                    province,\n                    postal_code,\n                    country\n                ) VALUES ($1, $2, $3, $4, $5, $6)\n                RETURNING billing_address_id\n            ",
  "parameters": [
    "68fd3eef-9f69-4fe9-a951-d9c540915425",
    "123 Main St",
    "Test City",
    "Test State",
    "12345",
    "Test Country"
  ],
  "driverError": {
    "length": 363,
    "name": "error",
    "severity": "ERROR",
    "code": "23502",
    "detail": "Failing row contains (c60e2ff7-373f-4b02-9c52-8e76535f9a76, 68fd3eef-9f69-4fe9-a951-d9c540915425, null, 123 Main St, null, 12345, Test City, Test State, Test Country).",
    "schema": "public",
    "table": "billing_address",
    "column": "property_id",
    "file": "execMain.c",
    "line": "2009",
    "routine": "ExecConstraints"
  },
  "length": 363,
  "severity": "ERROR",
  "code": "23502",
  "detail": "Failing row contains (c60e2ff7-373f-4b02-9c52-8e76535f9a76, 68fd3eef-9f69-4fe9-a951-d9c540915425, null, 123 Main St, null, 12345, Test City, Test State, Test Country).",
  "schema": "public",
  "table": "billing_address",
  "column": "property_id",
  "file": "execMain.c",
  "line": "2009",
  "routine": "ExecConstraints",
  "stack": "QueryFailedError: null value in column \"property_id\" of relation \"billing_address\" violates not-null constraint\n    at PostgresQueryRunner.query (C:\\Users\\dange\\fieldhive 3.0\\node_modules\\.pnpm\\typeorm@0.3.20_pg@8.13.1_ts-node@10.9.2_@types+node@20.17.1_typescript@5.6.3_\\src\\driver\\postgres\\PostgresQueryRunner.ts:331:19)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at DataSource.query (C:\\Users\\dange\\fieldhive 3.0\\node_modules\\.pnpm\\typeorm@0.3.20_pg@8.13.1_ts-node@10.9.2_@types+node@20.17.1_typescript@5.6.3_\\src\\data-source\\DataSource.ts:538:20)\n    at C:\\Users\\dange\\fieldhive 3.0\\packages\\api\\src\\routes\\account.routes.ts:149:44"
}
[2024-10-25 21:42:48] error: Uncaught Exception: listen EADDRINUSE: address already in use :::3004
{
  "code": "EADDRINUSE",
  "errno": -4091,
  "syscall": "listen",
  "address": "::",
  "port": 3004,
  "stack": "Error: listen EADDRINUSE: address already in use :::3004\n    at Server.setupListenHandle [as _listen2] (node:net:1904:16)\n    at listenInCluster (node:net:1961:12)\n    at Server.listen (node:net:2063:7)\n    at new WebSocketServer (C:\\Users\\dange\\fieldhive 3.0\\node_modules\\.pnpm\\ws@8.18.0\\node_modules\\ws\\lib\\websocket-server.js:102:20)\n    at createWebSocketServer (C:\\Users\\dange\\fieldhive 3.0\\packages\\api\\src\\index.ts:37:17)\n    at startServer (C:\\Users\\dange\\fieldhive 3.0\\packages\\api\\src\\index.ts:100:21)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"
}
